workflows:
  ios-workflow:
    name: Build iOS .ipa for Compose Multiplatform
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_WORKSPACE: "iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
      xcode: latest
      cocoapods: default
      java: 17
      kotlin: latest

    scripts:
      - name: Set up environment
        script: |
          echo "Setting up environment..."
          cd $CM_BUILD_DIR
          ls

      - name: Build iOS app
        script: |
          cd $CM_BUILD_DIR/iosApp
          pod install --repo-update
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -sdk iphoneos \
                     -configuration Debug \
                     -archivePath $CM_BUILD_DIR/build/iosApp.xcarchive \
                     archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/iosApp.xcarchive \
                     -exportOptionsPlist $CM_BUILD_DIR/iosApp/ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build/ipa

    artifacts:
      - build/ipa/*.ipa

    publishing:
      email:
        recipients:
          - $CM_EMAIL
