workflows:
  ios-simulator:
    name: iOS Simulator build (no signing, for Appetize)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      java: 17
      cocoapods: default
      vars:
        IOS_DIR: "iosApp"
        SCHEME: "iosApp"   # change si ton scheme a un autre nom
        DERIVED: "$CM_BUILD_DIR/build/DerivedData"
        DEST: "platform=iOS Simulator,name=iPhone 15"
    scripts:
      - name: Prepare
        script: |
          set -e
          cd "$CM_BUILD_DIR/$IOS_DIR"
          if [ -f Podfile ]; then pod install --repo-update; fi
      - name: Build (workspace or project)
        script: |
          set -e
          cd "$CM_BUILD_DIR/$IOS_DIR"
          if compgen -G "*.xcworkspace" > /dev/null; then
            WSP=$(ls *.xcworkspace | head -n1)
            xcodebuild -workspace "$WSP" \
                       -scheme "$SCHEME" \
                       -configuration Debug \
                       -sdk iphonesimulator \
                       -destination "$DEST" \
                       -derivedDataPath "$DERIVED" \
                       clean build
          else
            PRJ=$(ls *.xcodeproj | head -n1)
            xcodebuild -project "$PRJ" \
                       -scheme "$SCHEME" \
                       -configuration Debug \
                       -sdk iphonesimulator \
                       -destination "$DEST" \
                       -derivedDataPath "$DERIVED" \
                       clean build
          fi
      - name: Zip .app for Appetize
        script: |
          set -e
          APP_DIR="$DERIVED/Build/Products/Debug-iphonesimulator"
          APP_PATH=$(find "$APP_DIR" -maxdepth 1 -type d -name "*.app" | head -n1)
          echo "Found app: $APP_PATH"
          mkdir -p "$CM_BUILD_DIR/artifacts"
          cd "$APP_DIR"
          zip -r "$CM_BUILD_DIR/artifacts/iosApp-simulator.zip" "$(basename "$APP_PATH")"
    artifacts:
      - artifacts/*.zip
