workflows:
  ios-simulator:
    name: "iOS Simulator build (no signing, for Appetize)"
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      java: 17
      cocoapods: default
      vars:
        IOS_DIR: "iosApp"
        SCHEME: "iosApp"   # ⚠️ change si ton scheme réel est différent
        DERIVED: "$CM_BUILD_DIR/build/DerivedData"
        DEST: "platform=iOS Simulator,name=iPhone 15"
    scripts:
      - name: "Debug - list iOS tree"
        script: |
          set -e
          ls -la "$CM_BUILD_DIR/$IOS_DIR"

      - name: "Prebuild Kotlin/Native framework for simulator"
        script: |
          set -e
          cd "$CM_BUILD_DIR"
          chmod +x ./gradlew || true
          # Build le framework K/N pour l’arch simulateur (arm64 sur Mac M2)
          ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64
          echo "List built frameworks:"
          ls -R composeApp/build

      - name: "Debug - list schemes from xcodeproj"
        script: |
          set -e
          cd "$CM_BUILD_DIR/$IOS_DIR"
          xcodebuild -list -project iosApp.xcodeproj

      - name: "Build simulator via xcodeproj (NOT workspace)"
        script: |
          set -e
          cd "$CM_BUILD_DIR/$IOS_DIR"
          xcodebuild -project iosApp.xcodeproj \
                     -scheme "$SCHEME" \
                     -configuration Debug \
                     -sdk iphonesimulator \
                     -destination "$DEST" \
                     -derivedDataPath "$DERIVED" \
                     clean build

      - name: "Zip .app for Appetize"
        script: |
          set -e
          APP_DIR="$DERIVED/Build/Products/Debug-iphonesimulator"
          APP_PATH=$(find "$APP_DIR" -maxdepth 1 -type d -name "*.app" | head -n1)
          echo "Found app: $APP_PATH"
          test -d "$APP_PATH"
          mkdir -p "$CM_BUILD_DIR/artifacts"
          cd "$APP_DIR"
          zip -r "$CM_BUILD_DIR/artifacts/iosApp-simulator.zip" "$(basename "$APP_PATH")"

    artifacts:
      - artifacts/*.zip
