workflows:
  ios-simulator:
    name: iOS Simulator build (no signing, for Appetize)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      java: 17
      cocoapods: default
      vars:
        IOS_DIR: "iosApp"
        SCHEME: "iosApp"    # <- change ici si ton scheme a un autre nom
        DERIVED: "$CM_BUILD_DIR/build/DerivedData"
        DEST: "platform=iOS Simulator,name=iPhone 15"
    scripts:
      - name: Debug: lister fichiers iOS
        script: |
          set -e
          ls -la "$CM_BUILD_DIR/$IOS_DIR"

      - name: Debug: lister schemes du .xcodeproj
        script: |
          set -e
          cd "$CM_BUILD_DIR/$IOS_DIR"
          xcodebuild -list -project iosApp.xcodeproj

      - name: Build simulateur via le .xcodeproj (PAS le workspace)
        script: |
          set -e
          cd "$CM_BUILD_DIR/$IOS_DIR"
          xcodebuild -project iosApp.xcodeproj \
                     -scheme "$SCHEME" \
                     -configuration Debug \
                     -sdk iphonesimulator \
                     -destination "$DEST" \
                     -derivedDataPath "$DERIVED" \
                     clean build

      - name: Zipper le .app pour Appetize
        script: |
          set -e
          APP_DIR="$DERIVED/Build/Products/Debug-iphonesimulator"
          APP_PATH=$(find "$APP_DIR" -maxdepth 1 -type d -name "*.app" | head -n1)
          echo "Found app: $APP_PATH"
          mkdir -p "$CM_BUILD_DIR/artifacts"
          cd "$APP_DIR"
          zip -r "$CM_BUILD_DIR/artifacts/iosApp-simulator.zip" "$(basename "$APP_PATH")"

    artifacts:
      - artifacts/*.zip
